"""Add difficulty_rating field to youtube_quiz_results

Revision ID: 14d79b20fe5d
Revises: 7046960d226a
Create Date: 2025-06-24 15:36:26.877770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d79b20fe5d'
down_revision: Union[str, Sequence[str], None] = '7046960d226a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_quiz_results', sa.Column('difficulty_rating', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_quiz_results', 'difficulty_rating')
    # ### end Alembic commands ###
