"""sync_schema

Revision ID: 35de82bf0e31
Revises: 3fa25416e3a8
Create Date: 2025-07-08 23:53:30.919063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35de82bf0e31'
down_revision: Union[str, Sequence[str], None] = '3fa25416e3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_tutor_sessions', sa.Column('session_summary', sa.Text(), nullable=True))
    op.add_column('ai_tutor_sessions', sa.Column('identified_misconceptions', sa.JSON(), nullable=True))
    op.add_column('ai_tutor_sessions', sa.Column('learning_goals_achieved', sa.JSON(), nullable=True))
    op.add_column('grading_sessions', sa.Column('attempts', sa.Integer(), nullable=True))
    op.add_column('grading_sessions', sa.Column('time_spent', sa.Integer(), nullable=True))
    op.add_column('grading_sessions', sa.Column('hint_used', sa.Boolean(), nullable=True))
    op.add_column('grading_sessions', sa.Column('solution_viewed', sa.Boolean(), nullable=True))
    op.add_column('grading_sessions', sa.Column('confidence_level', sa.Integer(), nullable=True))
    op.add_column('ncert_examples', sa.Column('difficulty', sa.Float(), nullable=True))
    op.add_column('ncert_examples', sa.Column('prerequisites', sa.JSON(), nullable=True))
    op.add_column('ncert_examples', sa.Column('skills_tested', sa.JSON(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('difficulty', sa.Float(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('prerequisites', sa.JSON(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('skills_tested', sa.JSON(), nullable=True))
    op.add_column('pyqs', sa.Column('difficulty', sa.Float(), nullable=True))
    op.add_column('pyqs', sa.Column('prerequisites', sa.JSON(), nullable=True))
    op.add_column('pyqs', sa.Column('skills_tested', sa.JSON(), nullable=True))
    op.add_column('student_users', sa.Column('learning_goals', sa.JSON(), nullable=True))
    op.add_column('student_users', sa.Column('knowledge_profile', sa.JSON(), nullable=True))
    op.add_column('student_users', sa.Column('learning_style', sa.String(), nullable=True))
    op.add_column('student_users', sa.Column('preferred_session_length', sa.Integer(), nullable=True))
    op.add_column('student_users', sa.Column('last_active', sa.DateTime(), nullable=True))
    op.add_column('youtube_quiz_results', sa.Column('skills_tested', sa.JSON(), nullable=True))
    op.add_column('youtube_quiz_results', sa.Column('confidence_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_quiz_results', 'confidence_level')
    op.drop_column('youtube_quiz_results', 'skills_tested')
    op.drop_column('student_users', 'last_active')
    op.drop_column('student_users', 'preferred_session_length')
    op.drop_column('student_users', 'learning_style')
    op.drop_column('student_users', 'knowledge_profile')
    op.drop_column('student_users', 'learning_goals')
    op.drop_column('pyqs', 'skills_tested')
    op.drop_column('pyqs', 'prerequisites')
    op.drop_column('pyqs', 'difficulty')
    op.drop_column('ncert_exercises', 'skills_tested')
    op.drop_column('ncert_exercises', 'prerequisites')
    op.drop_column('ncert_exercises', 'difficulty')
    op.drop_column('ncert_examples', 'skills_tested')
    op.drop_column('ncert_examples', 'prerequisites')
    op.drop_column('ncert_examples', 'difficulty')
    op.drop_column('grading_sessions', 'confidence_level')
    op.drop_column('grading_sessions', 'solution_viewed')
    op.drop_column('grading_sessions', 'hint_used')
    op.drop_column('grading_sessions', 'time_spent')
    op.drop_column('grading_sessions', 'attempts')
    op.drop_column('ai_tutor_sessions', 'learning_goals_achieved')
    op.drop_column('ai_tutor_sessions', 'identified_misconceptions')
    op.drop_column('ai_tutor_sessions', 'session_summary')
    # ### end Alembic commands ###
