"""Update ncert_examples schema with solutions field

Revision ID: 3d9f454a3bf7
Revises: df2475607bcc
Create Date: 2025-06-29 17:35:24.629107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d9f454a3bf7'
down_revision: Union[str, Sequence[str], None] = 'df2475607bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncert_examples', sa.Column('solution', sa.JSON(), nullable=True))
    op.drop_column('ncert_examples', 'marking_criteria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncert_examples', sa.Column('marking_criteria', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('ncert_examples', 'solution')
    # ### end Alembic commands ###
