"""sync_schema

Revision ID: 40a0392caa0a
Revises: 54fc9633aefc
Create Date: 2025-07-04 00:57:44.915939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40a0392caa0a'
down_revision: Union[str, Sequence[str], None] = '54fc9633aefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncert_exercises', sa.Column('solution', sa.JSON(), nullable=True))
    op.drop_column('ncert_exercises', 'marking_criteria')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncert_exercises', sa.Column('marking_criteria', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('ncert_exercises', 'solution')
    # ### end Alembic commands ###
