"""Add AI tutor sessions table

Revision ID: 54fc9633aefc
Revises: 3d9f454a3bf7
Create Date: 2025-07-04 02:23:38.553095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fc9633aefc'
down_revision: Union[str, Sequence[str], None] = '3d9f454a3bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
