"""improved tables

Revision ID: 7b4a7b79b863
Revises: 274a4ea8883a
Create Date: 2025-06-28 16:18:37.443924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4a7b79b863'
down_revision: Union[str, Sequence[str], None] = '274a4ea8883a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncert_examples', sa.Column('question_id', sa.String(), nullable=True))
    op.add_column('ncert_examples', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('ncert_examples', sa.Column('chapter', sa.String(), nullable=True))
    op.add_column('ncert_examples', sa.Column('question_type', sa.String(), nullable=True))
    op.add_column('ncert_examples', sa.Column('source_example_number', sa.Integer(), nullable=True))
    op.add_column('ncert_examples', sa.Column('source_question_number', sa.Integer(), nullable=True))
    op.add_column('ncert_examples', sa.Column('source_part_number', sa.Integer(), nullable=True))
    op.add_column('ncert_examples', sa.Column('question_text', sa.Text(), nullable=True))
    op.add_column('ncert_examples', sa.Column('answer', sa.Text(), nullable=True))
    op.add_column('ncert_examples', sa.Column('marking_criteria', sa.JSON(), nullable=True))
    op.add_column('ncert_examples', sa.Column('common_mistakes', sa.JSON(), nullable=True))
    op.add_column('ncert_examples', sa.Column('teacher_notes', sa.JSON(), nullable=True))
    op.drop_column('ncert_examples', 'solution')
    op.drop_column('ncert_examples', 'example_number')
    op.drop_column('ncert_examples', 'example')
    op.drop_column('ncert_examples', 'grade')
    op.add_column('ncert_exercises', sa.Column('question_id', sa.String(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('chapter', sa.String(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('question_type', sa.String(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('source_exercise_number', sa.String(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('source_question_number', sa.Integer(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('source_part_number', sa.Integer(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('question_text', sa.Text(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('answer', sa.Text(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('marking_criteria', sa.JSON(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('common_mistakes', sa.JSON(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('teacher_notes', sa.JSON(), nullable=True))
    op.drop_column('ncert_exercises', 'exercise_number')
    op.drop_column('ncert_exercises', 'solution')
    op.drop_column('ncert_exercises', 'exercise')
    op.add_column('pyqs', sa.Column('question_id', sa.String(), nullable=True))
    op.add_column('pyqs', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('pyqs', sa.Column('chapter', sa.String(), nullable=True))
    op.add_column('pyqs', sa.Column('question_type', sa.String(), nullable=True))
    op.add_column('pyqs', sa.Column('max_marks', sa.Integer(), nullable=True))
    op.add_column('pyqs', sa.Column('source_year', sa.Integer(), nullable=True))
    op.add_column('pyqs', sa.Column('source_question_number', sa.Integer(), nullable=True))
    op.add_column('pyqs', sa.Column('source_part_number', sa.Integer(), nullable=True))
    op.add_column('pyqs', sa.Column('question_text', sa.Text(), nullable=True))
    op.add_column('pyqs', sa.Column('total_marks', sa.Integer(), nullable=True))
    op.add_column('pyqs', sa.Column('marking_criteria', sa.JSON(), nullable=True))
    op.add_column('pyqs', sa.Column('common_mistakes', sa.JSON(), nullable=True))
    op.add_column('pyqs', sa.Column('teacher_notes', sa.JSON(), nullable=True))
    op.alter_column('pyqs', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('pyqs', 'year')
    op.drop_column('pyqs', 'difficulty')
    op.drop_column('pyqs', 'question')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyqs', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('pyqs', sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pyqs', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('pyqs', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('pyqs', 'teacher_notes')
    op.drop_column('pyqs', 'common_mistakes')
    op.drop_column('pyqs', 'marking_criteria')
    op.drop_column('pyqs', 'total_marks')
    op.drop_column('pyqs', 'question_text')
    op.drop_column('pyqs', 'source_part_number')
    op.drop_column('pyqs', 'source_question_number')
    op.drop_column('pyqs', 'source_year')
    op.drop_column('pyqs', 'max_marks')
    op.drop_column('pyqs', 'question_type')
    op.drop_column('pyqs', 'chapter')
    op.drop_column('pyqs', 'subject')
    op.drop_column('pyqs', 'question_id')
    op.add_column('ncert_exercises', sa.Column('exercise', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('ncert_exercises', sa.Column('solution', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ncert_exercises', sa.Column('exercise_number', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('ncert_exercises', 'teacher_notes')
    op.drop_column('ncert_exercises', 'common_mistakes')
    op.drop_column('ncert_exercises', 'marking_criteria')
    op.drop_column('ncert_exercises', 'answer')
    op.drop_column('ncert_exercises', 'question_text')
    op.drop_column('ncert_exercises', 'source_part_number')
    op.drop_column('ncert_exercises', 'source_question_number')
    op.drop_column('ncert_exercises', 'source_exercise_number')
    op.drop_column('ncert_exercises', 'question_type')
    op.drop_column('ncert_exercises', 'chapter')
    op.drop_column('ncert_exercises', 'subject')
    op.drop_column('ncert_exercises', 'question_id')
    op.add_column('ncert_examples', sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ncert_examples', sa.Column('example', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('ncert_examples', sa.Column('example_number', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ncert_examples', sa.Column('solution', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('ncert_examples', 'teacher_notes')
    op.drop_column('ncert_examples', 'common_mistakes')
    op.drop_column('ncert_examples', 'marking_criteria')
    op.drop_column('ncert_examples', 'answer')
    op.drop_column('ncert_examples', 'question_text')
    op.drop_column('ncert_examples', 'source_part_number')
    op.drop_column('ncert_examples', 'source_question_number')
    op.drop_column('ncert_examples', 'source_example_number')
    op.drop_column('ncert_examples', 'question_type')
    op.drop_column('ncert_examples', 'chapter')
    op.drop_column('ncert_examples', 'subject')
    op.drop_column('ncert_examples', 'question_id')
    # ### end Alembic commands ###
