"""improved tables

Revision ID: 8e4f92965b3c
Revises: ea7838e87cbf
Create Date: 2025-06-28 17:25:56.732276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4f92965b3c'
down_revision: Union[str, Sequence[str], None] = 'ea7838e87cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncert_examples', sa.Column('grade', sa.String(), nullable=True))
    op.add_column('pyqs', sa.Column('grade', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pyqs', 'grade')
    op.drop_column('ncert_examples', 'grade')
    # ### end Alembic commands ###
