"""new_image

Revision ID: ae5db8db0f46
Revises: 35de82bf0e31
Create Date: 2025-07-30 02:07:14.326845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae5db8db0f46'
down_revision: Union[str, Sequence[str], None] = '35de82bf0e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ncert_examples', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('ncert_exercises', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('pyqs', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pyqs', 'image_url')
    op.drop_column('ncert_exercises', 'image_url')
    op.drop_column('ncert_examples', 'image_url')
    # ### end Alembic commands ###
