"""add_user_feedback_table

Revision ID: b8d2e87351dc
Revises: 35de82bf0e31
Create Date: 2025-08-01 18:38:12.064941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d2e87351dc'
down_revision: Union[str, Sequence[str], None] = '35de82bf0e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ncert_examples', 'image_url')
    op.drop_column('ncert_exercises', 'image_url')
    op.drop_column('pyqs', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pyqs', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ncert_exercises', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ncert_examples', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
